name: countdown-bot

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE=postgresql://postgres:${DB_PASSWORD}@db:5432
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
